### ISSUE TITLE
1.1.5 works fine, 1.2.0 throws ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bertyhell** [amelki/json-pretty-html#7]
Error thown for 1.2.0:
```
C:\...\dist-test\node_modules\json-pretty-html\dist\bundle.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,n){"object"==typeof exports&&"object"==typeof module?module.exports=n():"function"==typeof define&&define.amd?define([],n):"object"==typeof exports?exports.prettyPrint=n():t.prettyPrint=n()}(window,function(){return function(t){var n={};function e(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return t[r].call(o.exports,o,o.exports,e),o.l=!0,o.exports}return e.m=t,e.c=n,e.d=function(t,n,r){e.o(t,n)||Object.defineProperty(t,n,{enumerable:!0,get:r})},e.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},e.t=function(t,n){if(1&n&&(t=e(t)),8&n)return t;if(4&n&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(e.r(r),Object.defineProperty(r,"default",{enumerable:!0,val

ReferenceError: window is not defined
    at Object.<anonymous> (C:\...\dist-test\node_modules\json-pretty-html\dist\bundle.js:1:266)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\...\dist-test\test\test-utils\html-output-helpers.js:6:20)
    at Module._compile (module.js:652:30)
Waiting for the debugger to disconnect...

Process finished with exit code 1
```
![image](https://user-images.githubusercontent.com/1710840/47729090-d4809300-dc5f-11e8-92f4-8e358841b2fe.png)

The package works fine for version 1.1.5

The way I import the package in typescript:
```
const prettyHtml = require('json-pretty-html').default;
```

The way I use it:
```
prettyHtml(obj)
```

**Comment by rubenhak** [comment]
+1

**Comment by bertyhell** [comment]
> +1

Please use the thumbs up for existing answers, otherwise, everyone in the thread gets a notification which gets very spammy after a while.

![image](https://user-images.githubusercontent.com/1710840/48553870-173b9f80-e8dd-11e8-8616-f4ba1e536420.png)

**Comment by BlackHole1** [comment]
+1
Is it solved?

**Comment by BlackHole1** [comment]
Is a packaged problem, It does not support ssr

**Comment by BlackHole1** [comment]
Hi, guys. I have already submitted pr. Now it is waiting for @amelki  to mr

**Comment by BlackHole1** [comment]
I sent a package to solve the problem temporarily, and before mr, I can use this package as a substitute.
https://www.npmjs.com/package/json-pretty-html-fix

**Comment by amelki** [comment]
just published 1.1.6 with the fix. Thanks guys!
